### ISSUE TITLE
`HTMLOptionCtrl`

### ISSUE THREAD

**Issue by elycruz** [extensible-cms/ecms-rs#30]
Structure that represents an `HTMLSelectControl`'s 'Option' element.

## Todos

- [x] Builder 
  - [x] `value()`
  - [x] `label()`
  - [x] `validate()`
- [x] Struct
  - [x] `new()`
  - [x] `set_label()`
  - [x] `set_value()`
  - [x] `get_value()`
  - [x] `set_disabled()` When called child option elements' `set_disabled()` method should also get called this should subsequently toggle the `disabled` state on all descendant 'option' elements of a given 'optgroup' element.
  - [x] `is_opt_group` field(s) - Should allow control to have children, and behave as an 'optgroup'.
    - [x]  Verify interface on `HTMLOptGroupElement`, etc., before starting implementation. - Reference: https://html.spec.whatwg.org/multipage/form-elements.html#the-optgroup-element
- [x] ~~custom `disabled` 'builder' method - Methods should trigger `disabled` property toggling on all child elements.~~  No longer required.

**Comment by elycruz** [comment]
Issue completed in 'dev' branch (in commit [71b006a](https://github.com/extensible-cms/ecms-rs/commit/71b006a10301cb25488bae41c31530b129e99b6b)).
