### ISSUE TITLE
Terms Service (proof of concept)

### ISSUE THREAD

**Issue by elycruz** [extensible-cms/ecms-rs#32]
Terms service as a "reusable service" proof of concept - Actual CRUD processes are standalone (outside of http actions) for use in external (to parent) service compositions (e.g., Term Taxonomy Service etc.).

### Tasks

- [x] Standalone service declaration.
- [x] `create_term()` 
- [x] `read_term()`
- [x]  `update_term()`
- [x] `delete_term()`
- [x] (MVP) `index_action()` - with `limit`, and `offset` query params features.
- [x] `create_action()`
- [x] `read_action()`
- [x] `update_action()`
- [x] `delete_action()`
- [x] ~~Non-service endpoint unit test db writes should be transactional (wrapped in 'transaction' callbacks, etc.).~~ No longer required - Tests run linearly and as required.

**Comment by elycruz** [comment]
Implementation merged to main (in PR #33 ).
