### ISSUE TITLE
next: Roles Schema and Model

### ISSUE THREAD

**Issue by elycruz** [extensible-cms/ecms-rs#38]
## Todos

- [x] Db Table Schema
  - [x] `role` field. - follows `alias` input filter rule (e.g., slug format).
  - [x] `description` field - `TINYTEXT`.
- [x] Model
  - [x] `validate()` - Should follow same 
  - [ ] `create_*()` - Return type should include create row.
  - [x] `read_*()`
  - [ ] `update_*()` - Return type should include updated row.
  - [x] `delete_*()`
